### ISSUE TITLE
Make eprintsug/coversheets-latex and add to submods

### ISSUE THREAD

**Issue by cziaarm** [eprintsug/ulcc-core#12]
Add coversheets-latex plugin. An epm friendly version of the traditional coversheets capability of EPrints details: https://github.com/eprintsug/coversheets-latex close this when https://github.com/eprintsug/coversheets-latex/milestone/1 is reached

**Comment by mpbraendle** [comment]
We do have Coversheets running here on LaTeX (we did commission the work to pjw). Shall I upload the code, although very UZH specific?

**Comment by cziaarm** [comment]
Hi Martin,


We've had it running on some older servers for a while. The intention is to create a new git repo and put the old code in there in a structure that will allow us to include it in lib/epm.


I've created the empty repo (just now) https://github.com/eprintsug/coversheets-latex maybe you could share the UZH version there via a branch (if that's OK with Peter).


I suspect your stuff will be more up to date, if a little specific, but possibly the opportunity to do some merging to create a generally case that can be deployed relatively easily.


Cheers,


Rory




Rory McNicholl
Lead developer
Digital Archives & Research Technologies
University of London Computer Centre
Senate House
Malet Street
London
WC1E 7HU

t: +44 (0)20 7863 1344
e: rory.mcnicholl@london.ac.uk
w: http://www.ulcc.ac.uk/

The University of London is an exempt charity in England and Wales.
________________________________

**Comment by mpbraendle** [comment]
Hi Rory,

Peter is fine with that. Thanky you. I have to add some documentation, and also there are some problems to solve in our implementation (in most cases, it runs fine).

Cheers,
Martin
