### ISSUE TITLE
Add orcid support plugin(s)

### ISSUE THREAD

**Issue by cziaarm** [eprintsug/ulcc-core#14]
Three plugins are available for orcid, we should integrate these better into the ULCC EPrints service by default...

This may be as simple as including as sub moduless for ulcc-core (where we are not already), including in init scripts, helping with user-guides, documenting the config process internally

https://github.com/eprintsug/orcid_tier_1_importer (public api)

https://github.com/eprintsug/loginViaOrcid (public api, need to test)

https://github.com/eprintsug/orcidt2 (membership api, lots of conifg/setup)

**Comment by jesusbagpuss** [comment]
You missed: https://github.com/eprints/orcid_support

**Comment by cziaarm** [comment]
So I did! Cheers @jesusbagpuss 

[pivot]

Test eprints/orcid_support with a view to include as ulcc-core submodule

**Comment by cziaarm** [comment]
closed by b6964eb8e75328e2e3d08b52e0fc5b5dbc77122a
