### ISSUE TITLE
Sync with main eprints repository

### ISSUE THREAD

**Issue by denics** [eprintsug/ulcc-core#9]
Hi Guys, as things are advancing in the good direction, I would like to address the issue of syncing the code between this (great) simil vanilla eprints install and the main eprints/eprints repository. How should we proceed? are we going to merge their changes? are they going to merge ours?

**Comment by cziaarm** [comment]
Hi Denix, 

I've been watching the progress keenly here (slightly annoyed I've had no time to contribute more myself). Also I should say your own contributions to ulcc-core are mist appreciated!

 The plan would be to merge their core changes (we want to stay downstream of the main core) Hopefully there will be some bits of new parity, as I noticed that a number of Tim's pull requests were accepted.

In terms of timing I'd like to wait until the _new year_ before merging the master as per the instructions at the end of this.

http://eprintsug.github.io/ulcc-core/

The reason for this is that we have a number of customer deployments to do before then and should there be any post merge conflicts to sort out we would rather have a bit of breathing space to address them.

That said, feel free to create a new branch and merge on that in the meantime.

Thanks, 

Rory

Rory McNicholl
Lead developer
Digital Archives & Research Technologies
University of London Computer Centre
Senate House
Malet Street
London
WC1E 7HU

t: +44 (0)20 7863 1344
e: rory.mcnicholl@london.ac.uk
w: http://www.ulcc.ac.uk/

The University of London is an exempt charity in England and Wales.

**Comment by denics** [comment]
Hi Rory,

still interested in v3.3.15? I'm uploading my instances and so far, so good.

Denis

**Comment by cziaarm** [comment]
done
